TWORZENIE TABEL:

CREATE TABLE PRODUCENT(
ID_PROD BIGINT,
NAZWA VARCHAR(50),
KRAJ VARCHAR(50),
MIASTO VARCHAR(150),
KONCERN VARCHAR(50),
CZY_AKTYWNA BOOLEAN
);

CREATE TABLE SAMOCHOD(
ID_SAMOCHODU BIGINT,
MARKA VARCHAR(50),
MODEL VARCHAR(50),
GENERECJA VARCHAR(50),
SKRZYNIA_BIEGOW VARCHAR(30),
PALIWO VARCHAR(20),
ID_SILNIK BIGINT,
ID_WYPOSAZENIE BIGINT,
ID_OPON
CZY_MA_UBEZPIECZENIE BOOLEAN
);

CREATE TABLE SILNIK(
ID_SILNIK BIGINT,
NAZWA TEXT,
ROCZNIK INT,
IL_TLOK SMALLINT,
CZY_WOLNOSACY BOOLEAN,
OBJETOSC_CM3 INT,
IL_KM INT,
MOC INT
);

CREATE TABLE WYPOSAZENIE(
ID_WYPOSAZENIE BIGINT,
TAPICERKA VARCHAR(10),
KLIMATYZACJA BOOLEAN,
TEMPOMAT BOOLEAN,
OGRZEWANIE_POSTOJOWE BOOLEAN,
NAWIGACJA BOOLEAN,
SYSTEM_AUDIO BOOLEAN,
GRZANE_FOTELE BOOLEAN,
REGULOWANE_SIEDZENIA BOOLEAN,
CZUJNIK_DESZCZU BOOLEAN,
SWIATLA_KSENONOWE BOOLEAN
);

CREATE TABLE OPONY(
ID_OPONY BIGINT,
TYP_OPONY VARCHAR(30),
SZEROKOSC INT,
KONSTRUKCJA VARCHAR(5)
PROFIL INT,
SREDNICA_FELGI FLOAT,
WSKAZNIK_PREDKOSCI VARCHAR(5)
);

CREATE TABLE KLIENCI(
ID_KLIENTA BIGINT,
IMIE TEXT,
NAZWISKO TEXT,
KRAJ VARCHAR(100),
MIASTO VARCHAR(100),
ULICA TEXT,
EMAIL TEXT,
TEL_NUMER TEXT,
CZY_MA_ZAMOWINIE BOOLEAN,
ID_ZAMOWIENIA BIGINT
);

CREATE TABLE ZAMOWIENIA(
ID_ZAMOWIENIA BIGINT,
ID_KLIENTA BIGINT,
ID_SAMOCHODU BIGINT,
DATA_ZLOZENIA_ZAMOWIENIA DATETIME,
DOD_INFORMACJE TEXT
);



INSERTOWANIE DANYCH:

Producent:

INSERT INTO PRODUCENT VALUES (1, 'Toyota', 'Japonia', 'Toyota', 'Toyota Motor Corporation', TRUE);
INSERT INTO PRODUCENT VALUES (2, 'Volkswagen', 'Niemcy', 'Wolfsburg', 'Volkswagen Group', TRUE);
INSERT INTO PRODUCENT VALUES (3, 'Ford', 'USA', 'Detroit', 'Ford Motor Company', FALSE);

Silniki:

INSERT INTO SILNIK VALUES (1, 'V6 Turbo', 2020, 6, FALSE, 3000, 350, 450);
INSERT INTO SILNIK VALUES (2, 'EcoBoost I4', 2022, 4, FALSE, 2000, 250, 300);
INSERT INTO SILNIK VALUES (3, 'V8 Naturally Aspirated', 2019, 8, TRUE, 5000, 450, 600);

Wyposażenie:

INSERT INTO WYPOSAZENIE VALUES (1, 'Skóra', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO WYPOSAZENIE VALUES (2, 'Tkanina', FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE);

Opony:

INSERT INTO OPONY VALUES (1, 'Letnie', 225, 'R', 45, 17.0, 'V');
INSERT INTO OPONY VALUES (2, 'Zimowe', 195, 'R', 55, 16.0, 'H');

Samochody:

INSERT INTO SAMOCHOD VALUES (1, 'Toyota', 'Camry', 'XV70', 'Automatyczna', 'Benzyna', 1, 1, 1, TRUE);
INSERT INTO SAMOCHOD VALUES (2, 'Ford', 'Mustang', 'GT', 'Manualna', 'Benzyna', 3, 2, 2, FALSE);

Klienci:

INSERT INTO KLIENCI VALUES (1, 'Jan', 'Kowalski', 'Polska', 'Warszawa', 'Warszawska 10', 'jan.kowalski@mail.com', '123456789', TRUE, 1);
INSERT INTO KLIENCI VALUES (2, 'Anna', 'Nowak', 'Polska', 'Kraków', 'Krakowska 5', 'anna.nowak@mail.com', '987654321', FALSE, NULL);

Zamówienia:

INSERT INTO ZAMOWIENIA VALUES (1, 1, 1, '2025-10-10 10:00:00', 'Pilne zamówienie');
INSERT INTO ZAMOWIENIA VALUES (2, 2, 2, '2025-09-15 14:30:00', 'Bez dodatkowych uwag');



KWERENDY:

Wszyscy klienci co mają zamówienie:

SELECT IMIE, NAZWISKO, EMAIL 
FROM KLIENCI 
WHERE CZY_MA_ZAMOWINIE = TRUE;

Lista producentów z Polski lub którzy mają aktywny koncern:

SELECT * FROM PRODUCENT 
WHERE KRAJ = 'Polska' OR CZY_AKTYWNA = TRUE;

Wszystkie silniki z więcej niż 4 tłoków:
SELECT NAZWA, IL_TLOK FROM SILNIK WHERE IL_TLOK > 4;

Wyświetlenie zamówień:

SELECT ID_ZAMOWIENIA, DATA_ZLOZENIA_ZAMOWIENIA FROM ZAMOWIENIA;

Samochody z manualną skrzynią biegów:

SELECT MARKA, MODEL FROM SAMOCHOD WHERE SKRZYNIA_BIEGOW = 'Manualna';

Klienci z Warszawy:

SELECT IMIE, NAZWISKO FROM KLIENCI WHERE MIASTO = 'Warszawa';



UPDATE:

Zmiana miasta klienta na Gdańsk:

UPDATE KLIENCI
SET MIASTO = 'Gdańsk'
WHERE ID_KLIENTA = 1;

Zmiana stanu zamówienia klienta:

UPDATE KLIENCI
SET CZY_MA_ZAMOWINIE = TRUE
WHERE NAZWISKO = 'Nowak';

Zmiana mocy silnika:

UPDATE SILNIK
SET MOC = 280
WHERE ID_SILNIK = 2;



DELETE:

Usuwanie klienta o ID 2:

DELETE FROM KLIENCI
WHERE ID_KLIENTA = 2;

Usuwanie zamówienia:

DELETE FROM ZAMOWIENIA
WHERE ID_ZAMOWIENIA = 1;

Usuwanie silnika:

DELETE FROM SILNIK
WHERE NAZWA = 'V8 Naturally Aspirated';
